#!/bin/sh

export CI_BUILD_SHA="x${CI_BUILD_REF:0:8}"

# Automatically login docker
docker() {
	if [ ! -e ~/.docker/config.json ]; then
		command docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
	fi
	command docker "$@"
}

docker_build_push() {
	echo Building docker image...
	docker build --pull -t $CI_REGISTRY_IMAGE:$1 .

	echo Pushing docker image...
	docker push $CI_REGISTRY_IMAGE:$1
}

docker_tag_push_to_staging() {
    echo Building docker image...
	docker build --pull  -t $CI_REGISTRY_IMAGE:$1 .
	
	echo Tagging docker image...
	docker tag $CI_REGISTRY_IMAGE:$1 $CI_REGISTRY_IMAGE:$2

	echo Pushing docker image...
	docker push $CI_REGISTRY_IMAGE:$2
}

docker_tag_push_to_production() {
    echo Building docker image...
	docker build --pull -t $CI_REGISTRY_IMAGE:$1 .
	
	echo Tagging docker image...
	docker tag $CI_REGISTRY_IMAGE:$1 $CI_REGISTRY_IMAGE:$2

	echo Pushing docker image...
	docker push $CI_REGISTRY_IMAGE:$2
}

